sudo: required
language: python
services:
  - docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - IMAGE_NAME=ubuntu-xenial-kde5-neon-stable-compile-enviroment
  - REPO=luzfcb/ubuntu-xenial-kde5-neon-stable-compile-enviroment

script:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -t $IMAGE_NAME -t $REPO:$TAG -f Dockerfile.dev .
  

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:$TRAVIS_BUILD_NUMBER
  - docker push $REPO
