sudo: required
language: python
services:
- docker
#cache:
#  directories:
#  - $CACHE_DIR
env:
  global:
  - CONTAINER_NAME=subtitlecomposer_builder
  - DOCKER_ORGANIZATION_NAME=luzfcb
  - DOCKER_IMAGE_NAME=ubuntu-xenial-kde5-neon-stable-compile-environment
  - DOCKER_IMAGE_VERSION=latest
  - DOCKER_IMAGE_FULL_NAME=${DOCKER_ORGANIZATION_NAME}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_VERSION}
  - CACHE_DIR=$HOME/.cache/docker
  - CACHE_FILE_BASE_DOCKER_IMAGE=${CACHE_DIR}/${DOCKER_IMAGE_NAME}.tar.gz
  - DOCKER_COMPOSE_VERSION=1.12.0
  - COMMIT=${TRAVIS_COMMIT::8}

before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
  $(lsb_release -cs) stable"
- sudo apt-get update -qq
- sudo apt-get install -qq docker-ce libnetfilter-queue-dev libpcap-dev iptables-dev realpath
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
#- if [ -f ${CACHE_FILE_BASE_DOCKER_IMAGE} ]; then gunzip -c ${CACHE_FILE_BASE_DOCKER_IMAGE} | docker load; fi


script:
- if [ "$TRAVIS_BRANCH" == "master" ]; then export TAG="latest"; else export TAG="$TRAVIS_BRANCH";
  fi
- docker-compose -f docker-compose.yml build --no-cache ${CONTAINER_NAME}
#- docker pull luzfcb/ubuntu-xenial-kde5-neon-stable-compile-environment:latest
#- if [ ! -f ${CACHE_FILE_BASE_DOCKER_IMAGE} ]; then docker save ${DOCKER_IMAGE_FULL_NAME} | gzip > ${CACHE_FILE_BASE_DOCKER_IMAGE}; fi
#- scripts/build
#- scripts/up
#- scripts/compile_snap

after_success:
- ls -la

#deploy:
#  skip_cleanup: true
#  provider: releases
#  api_key:    secure: KmY47KnhDHImZr1iYW4Ijug1io2dSgIDSY9uSO7OKpl/y+YDzYJcU5eqca5W/YlMKZ54Cofo+9jknUF5neamOSkdX+xiue1axi0e44KUvY3y1TjJqXiP7ItvH7brzqfhqOKuoR6RnTwYJTw+/oNfiqWGk2XnDg3lMuoGeeviULmLzPWx+BaiXKlIBvaQ0XvRJoQXYU7h/g928fUdUKLhG+QyDekh7+04Q5Bf0YZU6x/OxTvuZa29tt0yog34zcRfYDTzqUCnPWBJ8417+XlVbkZpss26mTdfU/WOB0YFgxkSz1TeXBj/pRm2tiijwDBrpokicCH4kMaUPVrcEd1HgaT9hkxGUa5fhNuWwpgNAD71wXRFMVU2wg3Kw4jC/HmDl7xbKra+Xh5N/4iySQtOUFhw97CNxGQSWkpecoSfkO2DS8LE50bVuliAManzKNKnG6PEkzNbtzmw04QAXooD1PedOZUSSvfMijfXdzcr4H7+mZ0uCIOUMS12+r+++JPDb/ZXC2rx3ka1wvhLdS7jv5t39+JuSeauKiMargxBnQqw7htbyL5g+A1BWYhsozD3GJSFxKyF/tu+1tnZcIPLSNQ3/O34QCfEGuy1A27PwiDJ3TslyrgsV7kjcPHsU+HS7rbFm0IuLKEvIgX82vDBa843IpcBX/MCyRC0Ezw+LJQ=
#  file: subtitlecomposer_0.6.4-disabled-speechplugins+git_amd64.snap
#  release-number: ${COMMIT}
#  on:
#    repo: luzfcb/subtitlecomposer-snap
