sudo: required
language: python
services:
  - docker
env:
  global:
  - secure: lZt+7kRPKArMa9vGNmRpQjFZw92zn1ii+VajJw0elNIVykndCqP2hH76sArCw7KEOt8IbPnB0oTIpqd2T+26zNPO50hQT73SoGF9RAoz/IMK+qVlqcNXlieN838GOE9jJnsaZnNG+QpAAnscc3i0laDOpPa0agjmBjPojUhKV90pHKI/573o/J4NzsUbDVWhNHGwIP38r9LDKTcayy0IbQ8yLk/cTYVCZj8KOljtYyhWsTTqInMLSkn8Lk5/xzaqf86YiOOl5IblGpZa03h6K62HKagBxLpcMBUqCxjAG7PePiJ8kJb2FeoJR+jO0tMMG9GtOm5lF2evej6iLKSk99Rsr7l4YiWkDPkkOZA+AzKxGmbYftZ0VTQ7/Eb0NiT2sulI/TpWqd7+Tf7TlzlRxy51nkxQBWMrBXS+8S9tJqJjiwRBdbsc9VWqFgKDGLDpTsn48jEmjYzHPCuUyGlZ8oJzqs5ecdapNJJ1gp2MPVcYpoPzHcfKq9Zxry55BITnAQkgao69xAZmPbk50o7przZxo9EFnXsNSaUN9RnX4q/OEJVjfTlRMEYfg6cDYkij2wlt+x+BC9ePKcXESpy/u1o0W1zm7oc2n/R+Oc68vH4uEOWfAB1V/PzSxVq7bPcUQQpzVdAU48i9eYAl4T2jKJeJPezaIT89FA/rPvklzuY=
  - secure: U9SL6WyGK+YT+vg96teLsDocP5jAhB2y7VT1ApaDFu4ZJRXE+PxTf9ZIRgLJCTjn2d7qK+LdsX60MlG2jqqWpAFJqDC1PR8uTZRSOCCegUf3Rdt+FqWkYi9jxMfwtpq0cvIncfxVchVqJdzT4HfSnX1hqIjZI6uqn9ZzKGMXOAG5h/QHVHmeR4XvZ0k/uM/9+soMdxjqK+EqzeIwrIK+63t9AbhEMZNWFuO6hHlK0lZpvfCl25tzn8Dn3FMwAQhBh/I0Hrxv7I2acGv/iXbotIK3CIK9SC+G3H2q7fd66CUGYWr+nDp+sdUmLFHE3/QrarIOqr/KGED12p7WnP/q/yweLeKRtermolyHvmIout82dV3D0/bD4/DLEFFIQsZxZCsxItv9ohIbydC8wAO5CjUCqvZVQiWGclRm07WP89GaN4Yp95XGZ+nmAudsAaDpgpWfWAZbqmmnPrWmKPdK0/AZj+KzqkY0Xq0aryzAu1/FRgqHtEu7iLEQ3tJxy9PWYz5RaGTZUy51yoXVWNzU8JOdvLNt5//w2Zn536tZKKyaRTXw+vtpHKbQWsgcL4dbwInmDEA4igC0o3fqScQL2N2HPOu8GN6X5ZqjKy+y/OFiu50Woe9MUbeQ7z2Cry61pdtEbHltrMGR/s69e6FNi+j8EM2/P4R60Yp9tdEdG9A=
  - secure: OS2McToPUeV9wsWqID5wVsDPgjZRH0T3fBOrybWw8P5chHEDTCKiu0PuWn5ATIBb7uVNiqOLg2Fm24Jq1jGrCr1v8Luail/ToJdYevBrtglO9nC2NtIInOnIbeT05JAj7fJ8pBLL13vZ/CWerIL6i0BubFFrmi8oIR5015tFpNyk3KfHjCrfHYMwMex5andfy0+YmXM3/WEu5hNuKOS+wWi2eHnoZiwcrWiiKqO7JsEhD4VLr3/vKoV4/SWStD/foDNlL9l2HnlDh2IqcjFdnYNVZcMmp+NErkqxPGtli+jUhLgPEZLyFOMiLfYKBU3Ja0ApwECre8qy1tqhCQfN1DGWQ3T0w+sf6eqOS0Vc34JP5TYfAqjH6nai9OGkoUtiu3mUmgWkwwcbdEa6W/kPNnr9/kuqmeE3xb1d1WaZHtvb5FYWAH3kkXvVBrM7pI/YfcCNSeHE8M5UvHGspgDxaDNAPBJp6ERVX4b5FcE+dILTScRDNqJ2TdqGmQKqp2TBeMHKMEkIlht41sk7cPa5FSuenHfCmF1EVj3Lda7VbVr4oX8hmJo0Hv7j+0GjySLENWfUE8WmhnakKeul8Vt+XGDg0euWDeWqtyMuPkmdeTpd4itnDpgN4Gd6hmOoqIZIAtuDOTvab1P4FiYarwNqNRawJT5xzQ6EJQgAmk7jXl0=
  - COMMIT=${TRAVIS_COMMIT::8}
  - IMAGE_NAME=ubuntu-xenial-kde5-neon-stable-compile-enviroment
  - REPO=luzfcb/ubuntu-xenial-kde5-neon-stable-compile-enviroment

script:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -t $IMAGE_NAME -t $REPO:$TAG -f Dockerfile.dev .
  

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:$TRAVIS_BUILD_NUMBER
  - docker push $REPO
