sudo: required
language: python
services:
- docker
env:
  global:
  - DOCKER_COMPOSE_VERSION: 1.11.2
  - COMMIT=${TRAVIS_COMMIT::8}
  - IMAGE_NAME=subtitlecomposer_builder
  - REPO=luzfcb/subtitlecomposer_builder
before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
  $(lsb_release -cs) stable"
- sudo apt-get update -qq
- sudo apt-get install -qq docker-ce libnetfilter-queue-dev libpcap-dev iptables-dev
- sudo rm /usr/local/bin/docker-compose
- sudo -H pip install "docker-compose==$DOCKER_COMPOSE_VERSION"
script:
- if [ "$TRAVIS_BRANCH" == "master" ]; then export TAG="latest"; else export TAG="$TRAVIS_BRANCH";
  fi
- scripts/up
- scripts/compile_snap

deploy:
  provider: releases
  api_key:
    secure: KmY47KnhDHImZr1iYW4Ijug1io2dSgIDSY9uSO7OKpl/y+YDzYJcU5eqca5W/YlMKZ54Cofo+9jknUF5neamOSkdX+xiue1axi0e44KUvY3y1TjJqXiP7ItvH7brzqfhqOKuoR6RnTwYJTw+/oNfiqWGk2XnDg3lMuoGeeviULmLzPWx+BaiXKlIBvaQ0XvRJoQXYU7h/g928fUdUKLhG+QyDekh7+04Q5Bf0YZU6x/OxTvuZa29tt0yog34zcRfYDTzqUCnPWBJ8417+XlVbkZpss26mTdfU/WOB0YFgxkSz1TeXBj/pRm2tiijwDBrpokicCH4kMaUPVrcEd1HgaT9hkxGUa5fhNuWwpgNAD71wXRFMVU2wg3Kw4jC/HmDl7xbKra+Xh5N/4iySQtOUFhw97CNxGQSWkpecoSfkO2DS8LE50bVuliAManzKNKnG6PEkzNbtzmw04QAXooD1PedOZUSSvfMijfXdzcr4H7+mZ0uCIOUMS12+r+++JPDb/ZXC2rx3ka1wvhLdS7jv5t39+JuSeauKiMargxBnQqw7htbyL5g+A1BWYhsozD3GJSFxKyF/tu+1tnZcIPLSNQ3/O34QCfEGuy1A27PwiDJ3TslyrgsV7kjcPHsU+HS7rbFm0IuLKEvIgX82vDBa843IpcBX/MCyRC0Ezw+LJQ=
  file: subtitlecomposer_0.6.4+git_amd64.snap
  on:
    repo: luzfcb/subtitlecomposer-snap
