version: '3.0'
services:
  subtitlecomposer_builder:
    tty: true
    stdin_open: true
    container_name: subtitlecomposer_builder
    build:
      context: .
      dockerfile: Dockerfile.dev
      args: 
        - "CONTAINER_USER=${USER}"
    image: luzfcb/ubuntu-xenial-kde5-neon-stable-compile-environment:latest
    volumes:
      - .:/app_src:rw
    #ports:
      #- 33412:33411

