version: '3.0'
services:
  subtitlecomposer_builder:
    tty: true
    stdin_open: true
    container_name: subtitlecomposer_builder
    build:
      context: .
      dockerfile: Dockerfile.dev
      args: 
        - "CONTAINER_USER=${USER}"
    image: subtitlecomposer_builder_image
    volumes:
      - sourcecode:/app_src:rw
    #ports:
      #- 33412:33411

volumes:
  sourcecode: 
    driver_opts:
      type: none
      device: ${PROJECT_DIR}
      o: bind

    
