#!/bin/bash
WORK_DIR="$(dirname "$0")"
PROJECT_DIR="$(dirname "$WORK_DIR")"
export PROJECT_DIR="$(realpath "$PROJECT_DIR")"

# shellcheck source=scripts/__dependencies_checks
. "${WORK_DIR}/__dependencies_checks"

cd $PROJECT_DIR
docker-compose -f docker-compose.yml down --volumes --remove-orphans
