name: subtitlecomposer # you probably want to 'snapcraft register <name>'
version: '0.6.4-disabled-speechplugins+git' # just for humans, typically '1.2+git' or '1.3.2'
summary: Subtitles editor for KDE # 79 char long summary
description: |
  A text-based subtitles editor for KDE supporting basic operations (text,
  time and style edition), realtime previewing and spell checking. Other
  fancy features are delaying all subtitles in the current subtitle file,
  checking errors or creating translations.
  .
  Different backends (GStreamer, MPlayer, Phonon or xine) can be used to play
  the realtime video preview which helps to synchronize the subtitles.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
#confinement: strict


apps:
  subtitlecomposer:
    command: qt5-launch subtitlecomposer
    plugs:
      - home # give us a dir in the user home
      - x11 # we run with xcb Qt platform for now
      - opengl # Qt/QML uses opengl
      - network # gethotnewstuff needs network IO
      - network-bind # gethotnewstuff needs network IO
      - unity7 # notifications
      - pulseaudio # sound notifications

parts:
#  sphinxbase:
#    source: https://github.com/cmusphinx/sphinxbase.git
#    source-type: git
#    plugin: autotools
#    configflags: [--enable-static=no, --prefix=/usr]
#  pocketsphinx:
#    after: [sphinxbase]
#    source: https://github.com/cmusphinx/pocketsphinx.git
#    source-type: git
#    plugin: autotools
#    configflags: [--enable-static=no, --prefix=/usr]
  qt5conf:
    build-packages: [dpkg-dev]
    plugin: make
    source: https://github.com/dplanella/qt5conf
    source-type: git
    source-branch: master
    prime:
       - bin/qt5-launch
       - etc/xdg/qtchooser/snappy-qt5.conf
  subtitlecomposer:
    source: https://github.com/luzfcb/subtitlecomposer.git
    source-type: git
    source-branch: disable-speechplugins
    plugin: cmake
    configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
    build-packages:
        - build-essential
        - cmake
        - debhelper
        - extra-cmake-modules
        - git
        - kdelibs5-dev
        - kross-dev
        - libglib2.0-dev
        - libgstreamer1.0-dev
        - libgstreamer-plugins-base1.0-dev
        - libkf5xmlgui-dev
        - libmpv-dev
        - libphonon4qt5-dev
        - libphonon4qt5experimental-dev
        - libpocketsphinx3
        - libpocketsphinx-dev
        - libsphinxbase3
        - libsphinxbase-dev
        - libx11-dev
        - libxine2-dev
        - libxml2-dev
        - mplayer
        - mpv
        - pkg-kde-tools
        - qtbase5-dev
#    stage-packages:
#        - mplayer
#        - libglib2.0-0
#        - libgstreamer-plugins-base1.0-0
#        - libgstreamer1.0-0
#        - libicu55
#        - libkf5codecs5
#        - libkf5completion5
#        - libkf5configcore5
#        - libkf5configgui5
#        - libkf5configwidgets5
#        - libkf5coreaddons5
#        - libkf5i18n5
#        - libkf5kiocore5
#        - libkf5kiofilewidgets5
#        - libkf5kiowidgets5
#        - libkf5krosscore5
#        - libkf5sonnetcore5
#        - libkf5sonnetui5
#        - libkf5textwidgets5
#        - libkf5widgetsaddons5
#        - libkf5xmlgui5
#        - libmpv1
#        - libphonon4qt5-4
#        - libqt5core5a
#        - libqt5gui5
#        - libqt5widgets5
#        - libstdc++6
#        - libgtk2.0-0
#     prime:
#        - usr/lib/x86_64-linux-gnu/*
    after: [qt5conf]
