name: my-snap-name # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Subtitles editor for KDE # 79 char long summary
description: |
  A text-based subtitles editor for KDE supporting basic operations (text,
  time and style edition), realtime previewing and spell checking. Other
  fancy features are delaying all subtitles in the current subtitle file,
  checking errors or creating translations.
  .
  Different backends (GStreamer, MPlayer, Phonon or xine) can be used to play
  the realtime video preview which helps to synchronize the subtitles.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
#confinement: strict

parts:
    # Qt
    # based on https://github.com/tjyrinki/qt58
    # Thanks to Timo Jyrinki (@tjyrinki)
    qt:
        plugin: autotools2
        source-type: git
        source: https://code.qt.io/qt/qt5.git
        source-tag: "v5.8.0"
        #source-branch: 5.7.1
        build-attributes: ["no-system-libraries"]
        after: [qt-dependencies]
        configflags:        # config flags: for arm64, -opengl es2 platform linux-g++
            - -prefix
            - $SNAPCRAFT_PART_INSTALL/lib/qt5
            - -bindir
            - $SNAPCRAFT_PART_INSTALL/usr/bin
            - -release
            - -confirm-license
            - -opensource
            - -plugin-sql-mysql
            - -plugin-sql-odbc
            - -plugin-sql-psql
            - -plugin-sql-sqlite
            - -no-sql-sqlite2
            - -plugin-sql-tds
            - -system-sqlite
            - -platform
            - linux-g++-64
            - -system-harfbuzz
            - -system-zlib
            - -system-libpng
            - -system-libjpeg
            - -openssl
            - -no-rpath
            - -verbose
            - -optimized-qmake
            - -dbus-linked
            - -strip
            - -qpa
            - xcb
            - -xcb
            - -glib
            - -icu
            - -accessibility
            - -no-compile-examples
            - -no-directfb
            - -gstreamer
            - "1.0"
            - -opengl
            - desktop
            - -nomake
            - examples
            - -nomake
            - tests
            - -skip
            - qtquick1
            - -skip
            - qtwayland
            - -skip
            - qtwebengine
            - -skip
            - qtwebview
            - -skip
            - qtwebkit
            - -skip
            - qtwebkit-examples
    # Qt dependencies
    qt-dependencies:
        plugin: dump
        # From deb packaging build deps
        build-packages:
            - g++
            - freetds-dev
            - gdb
            - libasound2-dev
            - libatspi2.0-dev
            - libcups2-dev
            - libdbus-1-dev
            - libfontconfig1-dev
            - libfreetype6-dev
            - libgbm-dev
            - libgl1-mesa-dev
            - libgles2-mesa-dev
            - libglib2.0-dev
            - libglu1-mesa-dev
            - libgstreamer-plugins-base1.0-dev
            - libgstreamer1.0-dev
            - libgtk2.0-dev
            - libharfbuzz-dev
            - libicu-dev
            - libinput-dev
            - libjpeg-dev
            - libmtdev-dev
            - libmysqlclient-dev
            - libpcre3-dev
            - libpng12-dev
            - libpq-dev
            - libproxy-dev
            - libpulse-dev
            - libsqlite3-dev
            - libssl-dev
            - libudev-dev
            - libx11-dev
            - libx11-xcb-dev
            - libxcb-icccm4-dev
            - libxcb-image0-dev
            - libxcb-keysyms1-dev
            - libxcb-randr0-dev
            - libxcb-render-util0-dev
            - libxcb-render0-dev
            - libxcb-shape0-dev
            - libxcb-shm0-dev
            - libxcb-sync-dev
            - libxcb-xfixes0-dev
            - libxcb-xinerama0-dev
            - libxcb-xkb-dev
            - libxcb1-dev
            - libxext-dev
            - libxi-dev
            - libxkbcommon-dev
            - libxkbcommon-x11-dev
            - libxrender-dev
            - pkg-kde-tools
            - publicsuffix
            - unixodbc-dev
            - xvfb
            - zlib1g-dev
        # currently tailored from ubuntu 16.04 package names (mostly libpng etc may vary)
        stage-packages:
            - etc1tool # minimal package for depending on libpng regardless of Ubuntu version
            - fontconfig
            - icu-devtools
            - libc6
            - libcups2
            - libdbus-1-3
            - libdrm2
            - libegl1-mesa
            - libfontconfig1
            - libfreetype6
            - libgbm1
            - libgcc1
            - libgl1-mesa-dev
            - libgl1-mesa-glx
            - libgles2-mesa-dev
            - libglib2.0-0
            - libglu1-mesa-dev
            - libharfbuzz0b
            - libice6
            - libinput10
            - libjpeg8
            - libmtdev1
            - libpcre16-3
            - libproxy1v5
            - libsm6
            - libsqlite3-0
            - libstdc++6
            - libudev1
            - libx11-6
            - libx11-xcb1
            - libxcb1
            - libxcb-glx0
            - libxcb-icccm4
            - libxcb-image0
            - libxcb-keysyms1
            - libxcb-randr0
            - libxcb-render0
            - libxcb-render-util0
            - libxcb-shape0
            - libxcb-shm0
            - libxcb-sync1
            - libxcb-xfixes0
            - libxcb-xkb1
            - libxext-dev
            - libxi6
            - libxkbcommon0
            - libxkbcommon-x11-0
            - libxcb-xinerama0
            - libxrender1
            - perl
            - zlib1g
            - libdouble-conversion1v5
            - libpulse0

    subtitlecomposer:
      after: [qt]
      source: https://github.com/maxrd2/subtitlecomposer.git
      source-type: git
      plugin: cmake
      configflags: 
        - -DBUILD_TESTING=OFF
        - -DCMAKE_PREFIX_PATH=$SNAPCRAFT_STAGE/lib/qt5/lib/cmake/
        - -DCMAKE_BUILD_TYPE=Release
        - -DCMAKE_INSTALL_PREFIX=/
        - -DCMAKE_INSTALL_LIBDIR=lib/qt5/lib
        - -DKDE_INSTALL_QMLDIR=/lib/qt5/qml
        - -DECM_DIR=/usr/share/ECM/cmake
      build-packages:
          - build-essential
          - cmake
          - kdelibs5-dev
          - libglib2.0-dev
          - libgstreamer-plugins-base1.0-dev
          - libx11-dev
          - libxine2-dev
          - libxml2-dev
          - pkg-kde-tools
      stage-packages:
          - libc6
          - libgcc1
          - libglib2.0-0
          - libgstreamer-plugins-base1.0-0
          - libgstreamer1.0-0
          - libicu55
          - libkf5codecs5
          - libkf5completion5
          - libkf5configcore5
          - libkf5configgui5
          - libkf5configwidgets5
          - libkf5coreaddons5
          - libkf5i18n5
          - libkf5kiocore5
          - libkf5kiofilewidgets5
          - libkf5kiowidgets5
          - libkf5krosscore5
          - libkf5sonnetcore5
          - libkf5sonnetui5
          - libkf5textwidgets5
          - libkf5widgetsaddons5
          - libkf5xmlgui5
          - libmpv1
          - libphonon4qt5-4
          - libqt5core5a
          - libqt5gui5
          - libqt5widgets5
          - libstdc++6

    launcher:
      source: .
      plugin: dump
      organize:
          subtitlecomposer.launcher: bin/subtitlecomposer-launch
          snappy-qt5.conf: etc/xdg/qtchooser/snappy-qt5.conf
apps:
    subtitlecomposer:
        command: bin/subtitlecomposer-launch
        plugs: [
            unity7, # for desktop features
            opengl, # pretty obvious
            network, # access network
            network-bind, # more network access
            home, # access home directory for adding attachments etc
            browser-support, # make oxide happy in strict mode
            # silence QNetwork* classes. We could probably remove
            # this for unity8 as we can use the connectivity api
            network-observe,
            network-control
        ]
